services:
    reservation:
        build:
            context: .
            dockerfile: ./apps/reservation/Dockerfile
            target: development
        command: npm run start:debug reservation
        env_file: 
            - ./apps/reservation/.env
        ports:
            - '3000:3000'
            - '9229:9229'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db

    payments:
        build:
            context: .
            dockerfile: ./apps/payments/Dockerfile
            target: development
        command: npm run start:dev payments
        env_file: 
            - ./apps/payments/.env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db

    auth:
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
            target: development
        command: npm run start:dev auth
        ports:
            - '3001:3001'
        env_file:
            - ./apps/auth/.env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db

    notification:
        build:
            context: .
            dockerfile: ./apps/notification/Dockerfile
            target: development
        command: npm run start:dev notification
        env_file:
            - ./apps/notification/.env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db

    db:
        image: postgres
        container_name: db
        restart: always
        shm_size: 128mb
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
        volumes:
            - postgres_data:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
volumes:
    postgres_data:
