services:
    e2e:
        build:
            context: .
            dockerfile: ./e2e/Dockerfile
            target: e2e
        volumes:
            - ./e2e/specs:/usr/src/app/specs
        depends_on:
            - reservation
            - auth
            - notification
            - payments
            - db
    
    reservation:
        build:
            context: .
            dockerfile: ./apps/reservation/Dockerfile
            target: development
        command: npm run start:dev reservation
        env_file: 
            - ./apps/reservation/.env
        ports:
            - '3000:3000'
        depends_on:
            - db

    auth:
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
            target: development
        command: npm run start:dev auth
        ports:
            - '3001:3001'
        env_file:
            - ./apps/auth/.env
        depends_on:
            - db

    payments:
        build:
            context: .
            dockerfile: ./apps/payments/Dockerfile
            target: development
        command: npm run start:dev payments
        ports:
            - '3003:3003'
        env_file: 
            - ./apps/payments/.env
        depends_on:
            - db


    notification:
        build:
            context: .
            dockerfile: ./apps/notification/Dockerfile
            target: development
        command: npm run start:dev notification
        ports:
            - '3004:3004'
        env_file:
            - ./apps/notification/.env
        depends_on:
            - db

    db:
        image: postgres
        container_name: db
        restart: always
        shm_size: 128mb
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
